apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "skore-hub.fullname" . }}-db-migrations
  labels:
    {{- include "skore-hub.labels" . | nindent 4 }}
  annotations:
    # Run before the app is (re)deployed, on `helm install`/`helm upgrade`.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- with .Values.dbMigrations.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.dbMigrations.backoffLimit }}
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        {{- if .Values.skh.config.enabled }}
        checksum/skh-config: {{ include "skore-hub.configChecksum" . }}
        {{- end }}
      labels:
        {{- include "skore-hub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db-migrations
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: db-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.dbMigrations.resources | nindent 12 }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              {{ .Values.dbMigrations.command }}
          {{- if .Values.skh.envSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.skh.envSecret }}
          {{- end }}
          env:
            {{- include "skore-hub.configEnv" . | nindent 12 }}
            {{- include "skore-hub.env" . | nindent 12 }}
            {{- with .Values.skh.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- $hasMounts := or .Values.skh.config.enabled .Values.volumeMounts }}
          {{- if $hasMounts }}
          volumeMounts:
            {{- include "skore-hub.configVolumeMount" . | nindent 12 }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- $hasVolumes := or .Values.skh.config.enabled .Values.volumes }}
      {{- if $hasVolumes }}
      volumes:
        {{- include "skore-hub.configVolume" . | nindent 8 }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
